<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.manycoreapis</groupId>
        <artifactId>aholo-sdk-parent</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>aholo-sdk-examples</artifactId>
    <name>Aholo SDK Examples</name>
    <dependencies>
        <dependency>
            <groupId>com.manycoreapis</groupId>
            <artifactId>aholo-sdk-asset</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.manycoreapis</groupId>
            <artifactId>aholo-sdk-lux3d</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.manycoreapis</groupId>
            <artifactId>aholo-sdk-world</artifactId>
            <version>1.1.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.3.0</version>
            </plugin>
        </plugins>
    </build>
</project>
