package com.manycoreapis.sdk.lux3d.model;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/** Animation ids accepted by humanoid retarget. Source: Lux3D OpenAPI. */
public final class HumanoidAnimationIds {
    public static final Set<String> ALL;

    static {
        ALL = Collections.unmodifiableSet(new HashSet<String>(Arrays.asList(
            "A_TPose",
            "Dance_Loop",
            "Idle_Rail_Call",
            "Idle_TalkingPhone_Loop",
            "Idle_Talking_Loop",
            "Yes",
            "Crouch_Idle_Loop",
            "Idle_FoldArms_Loop",
            "Idle_Lantern_Loop",
            "Idle_Loop",
            "Idle_No_Loop",
            "Idle_Rail_Loop",
            "Idle_Torch_Loop",
            "ClimbUp_1m",
            "Crouch_Fwd_Loop",
            "Jog_Fwd_Loop",
            "Sprint_Loop",
            "Swim_Fwd_Loop",
            "Swim_Idle_Loop",
            "Walk_Formal_Loop",
            "Walk_Loop",
            "Jump_Land",
            "Jump_Loop",
            "Jump_Start",
            "NinjaJump_Idle_Loop",
            "NinjaJump_Land",
            "NinjaJump_Start",
            "Roll",
            "Slide_Exit",
            "Slide_Loop",
            "Slide_Start",
            "Sword_Attack",
            "Sword_Block",
            "Sword_Dash",
            "Sword_Heavy_Combo",
            "Sword_Idle",
            "Sword_Regular_A",
            "Sword_Regular_A_Rec",
            "Sword_Regular_B",
            "Sword_Regular_B_Rec",
            "Sword_Regular_C",
            "Sword_Regular_Combo",
            "Idle_Shield_Break",
            "Idle_Shield_Loop",
            "Shield_Dash",
            "Shield_OneShot",
            "Melee_Hook",
            "Melee_Hook_Rec",
            "Punch_Cross",
            "Punch_Jab",
            "Pistol_Aim_Down",
            "Pistol_Aim_Neutral",
            "Pistol_Aim_Up",
            "Pistol_Idle_Loop",
            "Pistol_Reload",
            "Pistol_Shoot",
            "Spell_Simple_Enter",
            "Spell_Simple_Exit",
            "Spell_Simple_Idle_Loop",
            "Spell_Simple_Shoot",
            "Chest_Open",
            "Consume",
            "Driving_Loop",
            "Farm_Harvest",
            "Farm_PlantSeed",
            "Farm_Watering",
            "Fixing_Kneeling",
            "Interact",
            "OverhandThrow",
            "PickUp_Table",
            "Push_Loop",
            "TreeChopping_Loop",
            "Walk_Carry_Loop",
            "LayToIdle",
            "Sitting_Enter",
            "Sitting_Exit",
            "Sitting_Idle_Loop",
            "Sitting_Talking_Loop",
            "Death01",
            "Hit_Chest",
            "Hit_Head",
            "Hit_Knockback",
            "Zombie_Idle_Loop",
            "Zombie_Scratch",
            "Zombie_Walk_Fwd_Loop"
        )));
    }

    private HumanoidAnimationIds() {}
}
